Update page.tsx
ImaraTv/imara.website pull request #13
Opened 2024-06-10 19:51 UTC by G-anna89

Add captcha to contact us form to prevent spam

2024-06-18 15:39 UTC, emuthomi commented on src/app/contact/page.tsx
> +                                    sitekey="6LeWq_UpAAAAABORtYdgSqOl4sDP6jDe7pmuyDTK"
@G-anna89 make this sitekey to be fetched from the .env

2024-06-18 15:44 UTC, emuthomi requested changes
@G-anna89 make this sitekey to be fetched from the .env

2024-06-26 10:59 UTC, mconyango approved these changes

2024-06-26 11:00 UTC, mconyango requested changes
As per Eric's suggestion

2024-06-26 12:34 UTC, merged